  webthings_gateway:
    image: mozillaiot/gateway:arm
    container_name: webthings_gateway
    network_mode: host
    x-ports:
      - "8080:8080"
      - "4443:4443"
    devices:
      - "${WEBTHINGS_DEVICE_PATH:?eg echo WEBTHINGS_DEVICE_PATH=/dev/serial0 >>~/IOTstack/.env}:/dev/ttyACM0"
    volumes:
      - ./volumes/webthings_gateway/share:/home/node/.mozilla-iot
